version: '3.3'
services:

    nginx:
      image: nginx
      depends_on:
      - account
      - client
      volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - target: 80
        protocol: tcp
        published: 80

    client:
      image: ayshamarty/account-client:latest
      build:
        context: ./Account-Maker-Front-End
        dockerfile: Dockerfile
      ports:
      - "3000:3000"

    account:
      image: ayshamarty/account-maker:latest
      build:
        context: ./Account-Maker
        dockerfile: Dockerfile
      ports:
      - "8090:8090"

    num-gen:
      image: ayshamarty/account-num-gen-high:latest
      build:
        context: ./Account-Maker-Num-Gen-High
        dockerfile: Dockerfile
      ports:
      - "8081:8081"

    prize-gen:
      image: ayshamarty/account-prize-gen:latest
      build:
        context: ./Account-Maker-Prize-Gen
        dockerfile: Dockerfile
      ports:
      - "8082:8082"

    consumer:
      image: ayshamarty/account-consumer:latest
      build:
        context: ./Account-Maker-Consumer
        dockerfile: Dockerfile
      ports:
      - "8084:8084"

    mongo:
      image: mongo
      ports:
      - "27017:27017"


    active-mq:
      image: webcenter/activemq
      ports:
      - "61616:61616"

